### ISSUE TITLE
The search bar doesn't have focus when zhudi starts up

### ISSUE THREAD

**Issue by lindenr** [Jiehong/Zhudi#13]
This is a bit subjective, but I think it would be better if the search bar had cursor focus when zhudi starts.

This would be better because you wouldn't have to click inside the search bar before you start typing.

Even better would be if the search bar **never** lost focus (in the "Dictionary" tab), even if you click on an entry. Then you could always type and the search bar would pick it up.

**Comment by lindenr** [comment]
Re the search bar always having focus - I've fixed this but will wait for you to approve the other PR before raising since it contains some of the same commits

**Comment by Jiehong** [comment]
It used to have focus on start up, actually. Perhaps the newest GTK has changed a bit that behaviour.

So I fully agree.
