### ISSUE TITLE
Zhudi is difficult to get started with

### ISSUE THREAD

**Issue by lindenr** [Jiehong/Zhudi#17]
I know there are good instructions in the README but I feel it could be still more user-friendly.

Coming bundled with cedict/cfdict would be better than nothing imo, but you might disagree. One plus is that updating zhudi would then be an easy way for me to update the dictionaries :P

Even having to first split the dictionary into bits would be better if it was seamless on first run. Something like running `zhudi -s mydict` could do the splitting, put the files in `~/.zhudi` instead of current directory, and then startup zhudi normally.

Maybe then it would be difficult to support multiple different dictionaries (e.g. both cfdict and cedict)? I think it could be made to work nicely. Let me know if you're interested and I'll make an attempt.

**Comment by Jiehong** [comment]
Hello @lindenr,

I have to agree with you there, back in the days, I already thought it wasn't great, but haven't touch it since then.

I think it would be great if zhudi was installable with pip instead of having to clone this repo, and maybe extra optional packages such as zhudi-dictionary-en, zhudi-dictionary-de, etc. to install the pre-processed dictionary for those languages directly (so no need to split the dictionary manually at first).

I don't mind accepting PRs for the defects you've opened (and I see one pending from a while back, I'll review it), but I don't have so much time for Zhudi anymore.

**Comment by lindenr** [comment]
Hi Jiehong, thanks for the reply. I'll fix up that PR for you then!

I think zhudi actually is pip-installable: `pip install git+https://github.com/Jiehong/Zhudi` worked fine for me.

**Comment by lindenr** [comment]
Can I ask - have you received my email to you? I sent one yesterday asking about the AUR package, but my emails often get dropped since we use a very small email server.

**Comment by Jiehong** [comment]
> Hi Jiehong, thanks for the reply. I'll fix up that PR for you then!
> 
> I think zhudi actually is pip-installable: `pip install git+https://github.com/Jiehong/Zhudi` worked fine for me.

I think that would be worth adding in the readme! Thanks for the info!

**Comment by Jiehong** [comment]
> Can I ask - have you received my email to you? I sent one yesterday asking about the AUR package, but my emails often get dropped since we use a very small email server.

I got only one, but not about AUR.

I orphaned the AUR package in Arch (https://aur.archlinux.org/packages/zhudi), mainly because I no longer use Arch this days.

Ask you question here if you want

**Comment by lindenr** [comment]
Ah yes, I saw it's orphaned but I don't know much about AUR. I do use arch and would be interested in taking over maintaining the AUR package if you don't want to, although maybe it's unnecessary with pip.

Regarding having dictionaries as separate packages (zhudi-dictionary-en etc) - what do you think about having them included in zhudi directly? I would be in favor of that personally, just for simplicity.

**Comment by Jiehong** [comment]
I think I didn't include the dictionaries at the time, mainly to not have to maintain using the latest version.

But it does make sense to have some "vetted" dictionaries ready to be used too.

Finally, a word about the license of those dictionaries might be important (just checking https://www.mdbg.net/chinese/dictionary?page=cedict for example)

**Comment by lindenr** [comment]
Very good point about licenses! I have no idea if zhudi would have to become creative commons licensed if it bundles cedict. Probably easier not to bother

**Comment by Jiehong** [comment]
I've checked the licenses for the German, English and French dictionaries, and they all 3 use the same allowing to use it directly, if we mention it in the app itself.

I'm starting to think it would be nice if we'd have all that data in a sqlite db (along with the preferences for that matter), and ship all 3 languages right away and propose an option to select the language.

But I'm busy migrating it to gtk 4 right now, so next time!

**Comment by Jiehong** [comment]
Closing this, as 3 dictionaries are now included by default on latest commit.

I won't tag the release yet, because the segmentation tab doesn't work anymore, though.
